import type { Metadata } from "next";
import "./globals.css";
import Wrapper from "@/components/Wrapper";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app with tailwindcss",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
