pipeline {
    agent any
    environment {
        CI = "true"
    }
    stages {
        stage('Add Deps') {
             steps {
                // sh './jenkins/scripts/install-deps.sh'
                sh 'npm install'
             }
        }
        stage('Test'){
            steps {
                sh 'npm run test'
            }
        }
        stage('Build'){
            steps {
                sh 'npm run build'
            }
        }
    }
}